"""Constants."""

from enum import IntEnum


class Limits(IntEnum):
    """Constants with the value type 'int'."""

    URL_TYPE_NAME_MAX_LENGTH = 100
    COLLECTION_NAME_MAX_LENGTH = 100
    COLLECTION_DESCRIPTION_MAX_LENGTH = 300
    BOOKMARK_TITLE_MAX_LENGTH = 100
    BOOKMARK_DESCRIPTION_MAX_LENGTH = 300
    BOOKMARK_IMAGE_MAX_LENGTH = 100
    COLLECTION_NUMBER_PER_PAGE = 10
    BOOKMARK_NUMBER_PER_PAGE = 10
