# Generated by Django 4.2.4 on 2023-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="date the collection was created",
                verbose_name="date of creation",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="time_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="date of the last update of the collection",
                verbose_name="date of update",
            ),
        ),
    ]
