# Generated by Django 4.2.4 on 2023-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0002_alter_collection_time_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="date the bookmark was created",
                verbose_name="date of creation",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="time_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="date of the last update of the bookmark",
                verbose_name="date of update",
            ),
        ),
    ]
