# Generated by Django 4.2.4 on 2023-08-22 17:46

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0003_alter_bookmark_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urltype",
            name="name",
            field=models.CharField(
                help_text="url type name",
                max_length=core.enums.Limits["URL_TYPE_NAME_MAX_LENGTH"],
                verbose_name="name",
            ),
        ),
    ]
