# Generated by Django 4.2.4 on 2023-08-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0005_alter_bookmark_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="add a description of the collection",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.TextField(
                help_text="bookmark page title", verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="url_type",
            field=models.ForeignKey(
                default=1,
                help_text="link type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookmarks",
                to="bookmarks.urltype",
                verbose_name="url type",
            ),
        ),
    ]
