# Generated by Django 4.2.4 on 2023-08-24 11:24

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookmarks",
            "0006_alter_bookmark_description_alter_bookmark_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="add a description of the collection",
                max_length=core.enums.Limits[
                    "COLLECTION_DESCRIPTION_MAX_LENGTH"
                ],
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.CharField(
                help_text="bookmark page title",
                max_length=core.enums.Limits["URL_TYPE_NAME_MAX_LENGTH"],
                verbose_name="title",
            ),
        ),
    ]
